services:
    mongodb:
        image: mongo:latest
        container_name: spring-mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express-ui
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
            ME_CONFIG_BASICAUTH_ENABLED: ${ME_CONFIG_BASICAUTH_ENABLED}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    
    petkeep-app:
        build: .
        container_name: petkeep-app
        restart: always
        ports:
            - 8080:8080
        environment:
            SPRING_MONGODB_URI: ${SPRING_MONGODB_URI}
            HUGGINGFACE_SECRET: ${HUGGINGFACE_SECRET}
        depends_on:
            - mongodb
        
volumes:
    mongo-data:
