spring.application.name=PetKeep
spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://root:spring-test1@localhost:27017/Petkeep_db?authSource=admin}
huggingface.secret=${HUGGINGFACE_SECRET}